---
apiVersion: v1
kind: Service
metadata:
  name: frontend-food-app-service
  namespace: food-app-ns
spec:
  selector: 
    app: frontend
  ports:
  - name: frontend-http
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: backend-food-app-service
  namespace: food-app-ns
spec:
  selector: 
    app: backend
  ports:
  - name: backend-http
    port: 8081
    targetPort: 8081
  type: LoadBalancer